### ISSUE TITLE
Milestone 4: stable timeseries release

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/vole-app#193]
- [x] #121
- [x] #192 
- [x] #190 
- [x] #189 
- [x] https://github.com/allen-cell-animated/volume-viewer/issues/78
- [x] https://github.com/allen-cell-animated/volume-viewer/issues/184
- [x] https://github.com/allen-cell-animated/volume-viewer/issues/178
- [x] #183 
- [x] https://github.com/allen-cell-animated/volume-viewer/issues/174
- [x] https://github.com/allen-cell-animated/volume-viewer/issues/143
- [x] #187 
- [x] #188 
- [x] #196
- [x] #197  
- [x] https://github.com/allen-cell-animated/volume-viewer/issues/189
- [x] #202 
- [x] #201 
- [x] #238 

bonus / stretch:
- [x] https://github.com/allen-cell-animated/volume-viewer/issues/156
- [x] #191
- [ ] #120
- [x] #80 
- [x] #131
